<a href="https://colab.research.google.com/github/lualua0909/DeepLearning-LDS8/blob/main/Week_1/example_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import tensorflow as tf
print(tf.__version__)

2.6.0


In [22]:
A = tf.constant(range(1, 13), shape=(2,2,3))
A

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [23]:
B = tf.reduce_sum(A)
B

<tf.Tensor: shape=(), dtype=int32, numpy=78>

In [24]:
B0 = tf.reduce_sum(A, 0)
B0

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 8, 10, 12],
       [14, 16, 18]], dtype=int32)>

In [25]:
B1 = tf.reduce_sum(A, 1) # Cộng tổng trên cột
B1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 5,  7,  9],
       [17, 19, 21]], dtype=int32)>

In [26]:
B2 = tf.reduce_sum(A, 2) # Cộng tổng trên dòng
B2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6, 15],
       [24, 33]], dtype=int32)>

In [31]:
# Tạo ra grayscale image
gray =  tf.random.uniform([2, 2], maxval=255, dtype='int32')
gray

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[185, 239],
       [240, 197]], dtype=int32)>

In [35]:
# Reshape grayscale img -> [n, 1]
gray = tf.reshape(gray, [gray.shape[0] * gray.shape[1], 1])
gray

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[185],
       [239],
       [240],
       [197]], dtype=int32)>

In [36]:
# Generate ra ảnh màu
color = tf.random.uniform([2, 2, 3], maxval=255, dtype='int32')
color

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[187,  62,  69],
        [230,  29, 154]],

       [[ 66,  76,  99],
        [ 40,  53, 138]]], dtype=int32)>

In [37]:
#Reshape color img
color = tf.reshape(color, [2 * 2, 3])
color

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[187,  62,  69],
       [230,  29, 154],
       [ 66,  76,  99],
       [ 40,  53, 138]], dtype=int32)>