<a href="https://colab.research.google.com/github/lualua0909/DeepLearning-LDS8/blob/main/Week_1/example_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.__version__)

2.6.0


In [2]:
x1 = tf.constant([1,2,3,4])
x2 = tf.constant([5,6,7,8])

In [3]:
result = tf.multiply(x1, x2)

In [4]:
result

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 5, 12, 21, 32], dtype=int32)>

In [5]:
tf.print(result)

[5 12 21 32]


In [16]:
#1D tensor
d1 = tf.ones((2,1,1))
tf.print(d1)

[[[1]]

 [[1]]]


In [9]:
#2D tensor
d2 = tf.ones((2,2))
tf.print(d2)

[[1 1]
 [1 1]]


In [20]:
#3D tensor
d3 = tf.ones((4,1,3))
tf.print(d3)

[[[1 1 1]]

 [[1 1 1]]

 [[1 1 1]]

 [[1 1 1]]]
